#!/bin/bash
iter=1
while [ 1 ]
do
    echo Iteration $iter
    sleep 1
    dig www.elastic.co > /dev/null
    dig 360.cn > /dev/null
    dig accuweather.com > /dev/null
    dig adobe.com > /dev/null
    dig amazon.com > /dev/null
    dig answers.yahoo.com > /dev/null
    dig apple.com > /dev/null
    dig baidu.com > /dev/null
    dig bbc.co.uk > /dev/null
    dig bbc.com > /dev/null
    dig bet365.com > /dev/null
    dig blogspot.com > /dev/null
    dig bongacams.com > /dev/null
    dig cnn.com > /dev/null
    dig cnzz.com > /dev/null
    dig coccoc.com > /dev/null
    dig craigslist.org > /dev/null
    dig dailymail.co.uk > /dev/null
    dig detail.tmall.com > /dev/null
    dig diply.com > /dev/null
    dig ebay.co.uk > /dev/null
    dig ebay.com > /dev/null
    dig facebook.com > /dev/null
    dig fc2.com > /dev/null
    dig github.com > /dev/null
    dig globo.com > /dev/null
    dig gmw.cn > /dev/null
    dig go2cloud.org > /dev/null
    dig google.com > /dev/null
    dig google.pl > /dev/null
    dig googleusercontent.com > /dev/null
    dig hao123.com > /dev/null
    dig imdb.com > /dev/null
    dig imgur.com > /dev/null
    dig instagram.com > /dev/null
    dig jd.com > /dev/null
    dig live.com > /dev/null
    dig microsoft.com > /dev/null
    dig msn.com > /dev/null
    dig Naver.com > /dev/null
    dig netflix.com > /dev/null
    dig news.google.com > /dev/null
    dig news.yahoo.co.jp > /dev/null
    dig nicovideo.jp > /dev/null
    dig nytimes.com > /dev/null
    dig office.com > /dev/null
    dig onclckds.com > /dev/null
    dig paypal.com > /dev/null
    dig popads.net > /dev/null
    dig qq.com > /dev/null
    dig quora.com > /dev/null
    dig rakuten.co.jp > /dev/null
    dig reddit.com > /dev/null
    dig samsung.com > /dev/null
    dig SimilarWeb > /dev/null
    dig sohu.com > /dev/null
    dig soso.com > /dev/null
    dig soundcloud.com > /dev/null
    dig stackoverflow.com > /dev/null
    dig t.co > /dev/null
    dig taobao.com > /dev/null
    dig tianya.cn > /dev/null
    dig tmall.com > /dev/null
    dig tumblr.com > /dev/null
    dig twitch.tv > /dev/null
    dig twitter.com > /dev/null
    dig Type > /dev/null
    dig uol.com.br > /dev/null
    dig vk.com > /dev/null
    dig walmart.com > /dev/null
    dig weibo.com > /dev/null
    dig whatsapp.com > /dev/null
    dig wikia.com > /dev/null
    dig wikipedia.com > /dev/null
    dig wikipedia.org > /dev/null
    dig wordpress.com > /dev/null
    dig www. > /dev/null
    dig www.360.cn > /dev/null
    dig www.accuweather.com > /dev/null
    dig www.adobe.com > /dev/null
    dig www.alibaba.com > /dev/null
    dig www.amazon.co.jp > /dev/null
    dig www.amazon.co.uk > /dev/null
    dig www.amazon.com > /dev/null
    dig www.amazon.de > /dev/null
    dig www.answers.yahoo.com > /dev/null
    dig www.apple.com > /dev/null
    dig www.baidu.com > /dev/null
    dig www.bbc.co.uk > /dev/null
    dig www.bbc.com > /dev/null
    dig www.bet365.com > /dev/null
    dig www.blogspot.com > /dev/null
    dig www.bongacams.com > /dev/null
    dig www.cnn.com > /dev/null
    dig www.cnzz.com > /dev/null
    dig www.coccoc.com > /dev/null
    dig www.craigslist.org > /dev/null
    dig www.dailymail.co.uk > /dev/null
    dig www.detail.tmall.com > /dev/null
    dig www.diply.com > /dev/null
    dig www.ebay.co.uk > /dev/null
    dig www.ebay.com > /dev/null
    dig www.facebook.com > /dev/null
    dig www.fc2.com > /dev/null
    dig www.github.com > /dev/null
    dig www.globo.com > /dev/null
    dig www.gmw.cn > /dev/null
    dig www.go2cloud.org > /dev/null
    dig www.google.ca > /dev/null
    dig www.google.co.id > /dev/null
    dig www.google.co.jp > /dev/null
    dig www.google.co.kr > /dev/null
    dig www.google.co.th > /dev/null
    dig www.google.co.uk > /dev/null
    dig www.google.com > /dev/null
    dig www.google.com.ar > /dev/null
    dig www.google.com.au > /dev/null
    dig www.google.com.br > /dev/null
    dig www.google.com.co > /dev/null
    dig www.google.com.eg > /dev/null
    dig www.google.com.hk > /dev/null
    dig www.google.com.ph > /dev/null
    dig www.google.com.sa > /dev/null
    dig www.google.com.tr > /dev/null
    dig www.google.com.tw > /dev/null
    dig www.google.com.ua > /dev/null
    dig www.google.com.vn > /dev/null
    dig www.google.de > /dev/null
    dig www.google.es > /dev/null
    dig www.google.fr > /dev/null
    dig www.google.it > /dev/null
    dig www.google.nl > /dev/null
    dig www.google.pl > /dev/null
    dig www.googleusercontent.com > /dev/null
    dig www.hao123.com > /dev/null
    dig www.imdb.com > /dev/null
    dig www.imgur.com > /dev/null
    dig www.instagram.com > /dev/null
    dig www.jd.com > /dev/null
    dig www.live.com > /dev/null
    dig www.microsoft.com > /dev/null
    dig www.msn.com > /dev/null
    dig www.Naver.com > /dev/null
    dig www.news.google.com > /dev/null
    dig www.news.yahoo.co.jp > /dev/null
    dig www.nicovideo.jp > /dev/null
    dig www.nytimes.com > /dev/null
    dig www.office.com > /dev/null
    dig www.onclckds.com > /dev/null
    dig www.paypal.com > /dev/null
    dig www.popads.net > /dev/null
    dig www.qq.com > /dev/null
    dig www.quora.com > /dev/null
    dig www.rakuten.co.jp > /dev/null
    dig www.reddit.com > /dev/null
    dig www.redtube.com > /dev/null
    dig www.samsung.com > /dev/null
    dig www.SimilarWeb > /dev/null
    dig www.sohu.com > /dev/null
    dig www.soso.com > /dev/null
    dig www.soundcloud.com > /dev/null
    dig www.stackoverflow.com > /dev/null
    dig www.t.co > /dev/null
    dig www.taobao.com > /dev/null
    dig www.tianya.cn > /dev/null
    dig www.tmall.com > /dev/null
    dig www.tumblr.com > /dev/null
    dig www.twitch.tv > /dev/null
    dig www.twitter.com > /dev/null
    dig www.Type > /dev/null
    dig www.uol.com.br > /dev/null
    dig www.vk.com > /dev/null
    dig www.walmart.com > /dev/null
    dig www.weibo.com > /dev/null
    dig www.whatsapp.com > /dev/null
    dig www.wikia.com > /dev/null
    dig www.wikipedia.org > /dev/null
    dig www.wordpress.com > /dev/null
    dig www.yahoo.co.jp > /dev/null
    dig www.yahoo.com > /dev/null
    dig www.youtube.com > /dev/null
    dig yahoo.co.jp > /dev/null
    dig yahoo.com > /dev/null
    dig youtube.com > /dev/null
    
    iter=$((iter+1))
done

